#
###################################
# Site wide configuration
####################################

port:                   2020
title:                  Olaolu Olawuyi
email:                  whiskydee@gmail.com
description:            Front-End Developer & UX Designer in Lagos.
home:                   "http://whizkydee.github.io"
baseurl:                ""
# url:                    "http://whizkydee.github.io"

exclude: ['node_modules']

twitter_username:       whizkydee
github_username:        whizkydee
facebook_name:          whizkydee

facebook_url:           https://facebook.com/whizkydee
twitter_url:            https://twitter.com/whizkydee
instagram_url:          https://instagram.com/whizkydee
github_url:             https://github.com/whizkydee
codepen_url:            https://codepen.io/whizkydee

#
###################################
# Jekyll configuration
####################################
#
timezone:          Africa/Lagos
excerpt_separator: More...
permalink: /:year/:month/:title

paginate: 10
paginate_path: "/page:num/"

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Olaolu Olawuyi
  avatar: blog-avatar.jpg
  job: "Web Developer/UX Designer"
  bio: "Creative Web Developer and UX Designer based in Lagos, Nigeria."
  email: whiskydee@gmail.com
  disqus-shortname:
  twitter: whizkydee
  facebook: whizkydee
  google:
    plus: #username
    analytics: UA-87284092-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: whizkydee
  linkedin: whizkydee
  instagram: whizkydee
  tumblr: whizkydee
  pinterest: whizkydee
  dribbble: whizkydee
  youtube: whizkydee
  flickr: whizkydee
  codepen: whizkydee

# Enable assets compression:
sass:
  style: compressed

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

# Gems
gems: [jekyll-paginate]
